### ISSUE TITLE
make gulp-util a dependency

### ISSUE THREAD

**Issue by erickmerchant** [KenPowers/gulp-cheerio#10]
I get "Error: Cannot find module 'gulp-util'" after upgrading to 0.6.1

**Comment by KenPowers** [comment]
Just published `0.6.2`. Sorry about that. Does that work for you?

**Comment by erickmerchant** [comment]
0.6.2 works great. Thanks for fixing this so quickly.

**Comment by KenPowers** [comment]
No problem.
